# Generated by Django 2.2.27 on 2022-02-09 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('last_active', '0001_initial'), ('last_active', '0002_define_id_field')]

    dependencies = [
        migrations.swappable_dependency(settings.LAST_SEEN_SITE_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LastActive',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(default='default', max_length=20)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.LAST_SEEN_SITE_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_active',),
                'unique_together': {('user', 'site', 'module')},
            },
        ),
    ]
