# Generated by Django 2.2.27 on 2022-02-09 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('last_active', '0001_0002_squashed_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastactive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_active', to=settings.AUTH_USER_MODEL),
        ),
    ]
